#!/usr/bin/env python3
"""Blueberry Tumble asset build: the code-drawn sheets (make_art.py) -> tiles, palettes, metatiles, maps and
sprites; the music (make_music.py) -> build/gen/blueberrytumble/assets.c + assets.h.

    build_assets.py --out build/gen/blueberrytumble [--art games/blueberrytumble/art] [--tileset IGNORED]

VRAM (tiles of 32 bytes; the house guideline is 64 KiB with the maps):
  0      BG1: the house UI kit (house_ui.h), the logo at LOGO_TILE
  640    BG4: the far mountains         768  BG3: the mid-ground (4 biomes)
  1280   BG2: the playfield (affine)    3072 OBJ: our sprites, then the kit's (KIT_OBJ_TILE)
MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft): games/blueberrytumble/LICENSE.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "games", "common", "tools"))
import rsasset  # noqa: E402
import house_style as hs  # noqa: E402
import make_art  # noqa: E402

VR_BG1, VR_BG4, VR_BG3, VR_BG2, VR_OBJ = 0, 640, 768, 1280, 3072
LOGO_TILE = 300                     # relative to BG1 (the kit uses 0..296)
KIT_OBJ_TILE = 400                  # the kit's sprites after ours
PAL_PF, PAL_FAR, PAL_MID, PAL_LOGO = 1, 5, 6, 4     # playfield 1-4 (a biome each), mid 6-7 (by biome parity)
OBJ_PAL = {"berry": 0, "props": 2, "propsb": 4, "snow": 5, "gold": 7}     # 1, 6: player 2; 3: the kit
P2_OF = {"berry": 1, "snow": 6}
P2_HUE = (0.55, 0.78, 0.36)         # blues -> raspberry reds (house_style.hue_swap)


def cells8(img, x0, y0, w, h):
    return [rsasset.cell(img, x0 + x * 8, y0 + y * 8, 8, 8) for y in range(h // 8) for x in range(w // 8)]


def arr16(name, data):
    return "const uint16_t %s[%d] = {%s};" % (name, len(data), ", ".join("0x%04x" % v for v in data))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    ap.add_argument("--tileset", default="", help="ignored (the tiles are code-drawn)")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    if not os.path.exists(os.path.join(a.art, "palettes.json")):
        make_art.write_all(a.art)
    pals = json.load(open(os.path.join(a.art, "palettes.json")))
    c = ["/* Generated by games/blueberrytumble/tools/build_assets.py. Do not edit. */", '#include "assets.h"\n']
    h = ["/* Generated by games/blueberrytumble/tools/build_assets.py. Do not edit. */",
         "#ifndef GM_ASSETS_H\n#define GM_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n",
         "#define VR_BG1 %d\n#define VR_BG4 %d\n#define VR_BG3 %d\n#define VR_BG2 %d\n#define VR_OBJ %d" %
         (VR_BG1, VR_BG4, VR_BG3, VR_BG2, VR_OBJ),
         "#define LOGO_TILE %d\n#define KIT_OBJ_TILE %d" % (LOGO_TILE, KIT_OBJ_TILE),
         "#define PAL_PF %d\n#define PAL_FAR %d\n#define PAL_MID %d\n#define PAL_LOGO %d" % (PAL_PF, PAL_FAR, PAL_MID, PAL_LOGO)]
    stats = []

    # ---- the playfield: role-indexed metatiles shared by the biomes (palette = biome) ----------------------------
    img = rsasset.load(os.path.join(a.art, make_art.SHEETS["playfield"]))
    names = pals["pf_tiles"]
    tiles, index = [[0] * 64], {tuple([0] * 64): (0, 0, 0)}
    metas = []
    for b in range(4):
        role = {rsasset.to555(tuple(col)): i + 1 for i, col in enumerate(pals["pf"][b])}
        assert len(role) == 15, "biome %d: two roles have the same RGB555 colour" % b
        row = []
        for m in range(len(names)):
            meta = []
            for t in rsasset.split_tiles(rsasset.cell(img, m * 16, b * 16, 16, 16)):
                idx = []
                for v in t:
                    if v is None:
                        idx.append(0)
                    elif v in role:
                        idx.append(role[v])
                    else:
                        raise SystemExit("playfield %s biome %d: colour %s is not one of the roles" % (names[m], b, v))
                key = tuple(idx)
                hit = index.get(key)
                if hit is None:
                    for hf, vf, f in ((1, 0, rsasset.hflip), (0, 1, rsasset.vflip),
                                      (1, 1, lambda x: rsasset.vflip(rsasset.hflip(x)))):
                        k2 = tuple(f(idx))
                        if k2 in index:
                            base = index[k2]
                            hit = (base[0], hf ^ base[1], vf ^ base[2])
                            break
                if hit is None:
                    tiles.append(idx)
                    hit = (len(tiles) - 1, 0, 0)
                    index[key] = hit
                meta.append(rsasset.rs_map(hit[0], PAL_PF + b, 0, hit[1], hit[2]))
            row += meta
        metas += row
    c.append(rsasset.c_bytes("gm_pf_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int gm_pf_tile_count = %d;" % len(tiles))
    c.append(arr16("gm_pf_meta", metas))
    pf_pal = []
    for b in range(4):
        pf_pal += [0] + [rsasset.to555(tuple(col)) for col in pals["pf"][b]]
    c.append(arr16("gm_pf_pal", pf_pal))
    h.append("enum { %s, MT_COUNT };" % ", ".join("MT_%s" % n.upper() for n in names))
    h.append("extern const uint8_t gm_pf_tiles[];\nextern const int gm_pf_tile_count;")
    h.append("extern const uint16_t gm_pf_meta[4 * MT_COUNT * 4];   /* [biome][metatile][4 entries] */")
    h.append("extern const uint16_t gm_pf_pal[4 * 16];")
    stats.append("playfield %d" % len(tiles))

    # ---- mid-ground: one 16 x 6 map per biome ------------------------------------------------------------------------
    img = rsasset.load(os.path.join(a.art, make_art.SHEETS["mid"]))
    mw, mh = make_art.MID_W // 8, make_art.MID_H // 8
    mtiles, mmaps, mpal = [], [], []
    extra = []
    for b in range(4):
        cells = cells8(img, 0, b * make_art.MID_H, make_art.MID_W, make_art.MID_H)
        n = len(cells)
        if b == 2:      # the meadows without the family share the meadows' palette: one conversion
            cells += cells8(img, 0, 4 * make_art.MID_H, make_art.MID_W, make_art.MID_H)
        r = rsasset.convert_bg(cells, 1, pal_base=PAL_MID + (b & 1), tile_base=len(mtiles), reserve_blank=(b == 0))
        mtiles += r.tiles
        mmaps += [m[0] for m in r.metas[:n]]
        if b == 2:
            extra = [m[0] for m in r.metas[n:]]
        mpal += rsasset.palette16(r.palettes[0])
    mmaps += extra                  # band 4: the meadows without the family
    mpal += mpal[2 * 16:3 * 16]
    c.append(rsasset.c_bytes("gm_mid_tiles", rsasset.tiles_bytes(mtiles)))
    c.append("const int gm_mid_tile_count = %d;" % len(mtiles))
    c.append(arr16("gm_mid_map", mmaps))
    c.append(arr16("gm_mid_pal", mpal))
    h.append("#define MID_W %d\n#define MID_H %d" % (mw, mh))
    h.append("extern const uint8_t gm_mid_tiles[];\nextern const int gm_mid_tile_count;")
    h.append("extern const uint16_t gm_mid_map[5 * MID_W * MID_H];   /* [band][row][col]: the biomes, then the meadows "
             "without the family */\nextern const uint16_t gm_mid_pal[5 * 16];")
    stats.append("mid %d" % len(mtiles))

    # ---- far mountains -------------------------------------------------------------------------------------------------
    img = rsasset.load(os.path.join(a.art, make_art.SHEETS["far"]))
    r = rsasset.convert_bg(cells8(img, 0, 0, make_art.FAR_W, make_art.FAR_H), 1, pal_base=PAL_FAR, tile_base=0)
    c.append(rsasset.c_bytes("gm_far_tiles", rsasset.tiles_bytes(r.tiles)))
    c.append("const int gm_far_tile_count = %d;" % len(r.tiles))
    c.append(arr16("gm_far_map", [m[0] for m in r.metas]))
    c.append(arr16("gm_far_pal", rsasset.palette16(r.palettes[0])))
    h.append("#define FAR_W %d\n#define FAR_H %d" % (make_art.FAR_W // 8, make_art.FAR_H // 8))
    h.append("extern const uint8_t gm_far_tiles[];\nextern const int gm_far_tile_count;")
    h.append("extern const uint16_t gm_far_map[FAR_W * FAR_H];\nextern const uint16_t gm_far_pal[16];")
    stats.append("far %d" % len(r.tiles))

    # ---- sprites ----------------------------------------------------------------------------------------------------------
    sheet = rsasset.load(os.path.join(a.art, make_art.SHEETS["sprites"]))
    otiles, rows, snames, opals = [], [], [], [0] * 128
    idx = 0
    for g in ("berry", "snow", "props", "propsb", "gold"):
        ents = [e for e in make_art.SPRITES if e[6] == g]
        frames = []
        for name, x, y, w, hh, n, _g in ents:
            frames += [rsasset.cell(sheet, x + i * w, y, w, hh) for i in range(n)]
        ro = rsasset.convert_obj(frames)
        if len(ro.palette) > 15:
            raise SystemExit("sprite group %s: %d colours" % (g, len(ro.palette)))
        p16 = rsasset.palette16(ro.palette)
        opals[OBJ_PAL[g] * 16:OBJ_PAL[g] * 16 + 16] = p16
        if g in P2_OF:
            rgb = [rsasset.rgb888(v) for v in p16[1:]]
            opals[P2_OF[g] * 16:P2_OF[g] * 16 + 16] = [0] + [rsasset.to555(v) for v in hs.hue_swap(rgb, *P2_HUE)]
        k = 0
        for name, x, y, w, hh, n, _g in ents:
            snames.append("SPR_%s = %d" % (name.upper(), idx))
            for f in range(n):
                first, fw, fh = ro.frames[k]
                rows.append("{%d, %d, %d, %d}" % (len(otiles) + first, fw, fh, OBJ_PAL[g]))
                k += 1
                idx += 1
        otiles += ro.tiles
    assert len(otiles) <= KIT_OBJ_TILE, "the sprites (%d tiles) overlap the kit's: raise KIT_OBJ_TILE" % len(otiles)
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(snames), idx))
    h.append("typedef struct gm_sprite_def { uint16_t tile; uint8_t w, h, pal; } gm_sprite_def;")
    h.append("extern const gm_sprite_def gm_spr[SPR_COUNT];")
    h.append("extern const uint8_t gm_obj_tiles[];\nextern const int gm_obj_tile_count;\nextern const uint16_t gm_obj_pals[128];")
    c.append("const gm_sprite_def gm_spr[SPR_COUNT] = {\n    " + ",\n    ".join(rows) + "};")
    c.append(rsasset.c_bytes("gm_obj_tiles", rsasset.tiles_bytes(otiles)))
    c.append("const int gm_obj_tile_count = %d;" % len(otiles))
    c.append(rsasset.c_u16("gm_obj_pals", opals))
    stats.append("OBJ %d" % len(otiles))

    # ---- the biome names (the gate's sign) ---------------------------------------------------------------------------
    c.append("const char *const gm_biome_names[4] = {%s};" % ", ".join('"%s"' % n for n in pals["biome_names"]))
    h.append("extern const char *const gm_biome_names[4];")

    # ---- the asset pack: the music --------------------------------------------------------------------------------------
    music_dir = os.path.join(a.out, "music")
    for old in glob.glob(os.path.join(music_dir, "*.mod")):
        os.remove(old)                  # no stale tracks in the pack
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    pack = [("music/" + os.path.basename(p), p) for p in sorted(glob.glob(os.path.join(music_dir, "*.mod")))]
    entries = []
    for i, (name, path) in enumerate(pack):
        data = open(path, "rb").read()
        c.append(rsasset.c_bytes("pack_%d" % i, data, static=True))
        entries.append('    {"%s", pack_%d, %d}' % (name, i, len(data)))
    c.append("const rs_asset_entry gm_assets[] = {\n" + ",\n".join(entries) + ",\n    {0, 0, 0}};")
    h.append("extern const rs_asset_entry gm_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: tiles %s, %d pack files -> %s" % (", ".join(stats), len(pack), a.out))


if __name__ == "__main__":
    main()
