#!/usr/bin/env python3
"""Bomber Mole asset build: sheets -> tiles/palettes/metatiles/sprites, levels
and music -> build/gen/bombermole/assets.c + assets.h.

    build_assets.py --out build/gen/bombermole [--art games/bombermole/art]

All rights reserved, 8BCraft.
"""
import argparse
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import sheets  # noqa: E402
import rsasset  # noqa: E402
import palette_variants  # noqa: E402

TERRAIN_PALS = 4          # BG palettes 1..4
PAL_PROPS = 5             # BG palette of the terrain-like props
PAL_FX, PAL_HUD = 6, 7    # BG palettes
PROPS_TILE_BASE = 192     # relative to the playfield layers' tile base
FX_TILE_BASE = 384
HUD_TILE_BASE = 512       # relative to BG1's tile base (the font is at 0)
OBJ_GROUPS = ["mole", "ferret", "cat", "boss", "bomb", "pickup", "prop", "critter"]  # = OBJ palettes 0-7
BOSSES = ["boss_cat", "boss_farmer", "boss_badger", "boss_fox", "boss_owl"]  # loaded into OBJ palette 3


def cname(s):
    return s.upper().replace("-", "_").replace(".", "_")


def frames_of(img, e, season=0):
    return [rsasset.cell(img, x, y, w, h) for (x, y, w, h) in sheets.frame_rects(e, season)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    img = {k: rsasset.load(os.path.join(a.art, v["file"])) for k, v in sheets.SHEETS.items()}
    c, h = [], []
    c.append("/* Generated by games/bombermole/tools/build_assets.py from %s. Do not edit. */" %
             os.path.relpath(a.art, ROOT))
    c.append('#include "assets.h"\n')
    h.append("/* Generated by games/bombermole/tools/build_assets.py. Do not edit. */")
    h.append("#ifndef BM_ASSETS_H\n#define BM_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n")
    h.append("#define TERRAIN_PALS %d\n#define PAL_FX %d\n#define PAL_HUD %d" % (TERRAIN_PALS, PAL_FX, PAL_HUD))
    h.append("#define FX_TILE_BASE %d\n#define HUD_TILE_BASE %d\n#define PROPS_TILE_BASE %d\n#define PAL_PROPS %d\n" %
             (FX_TILE_BASE, HUD_TILE_BASE, PROPS_TILE_BASE, PAL_PROPS))

    # ---- terrain (one tile set per season) --------------------------------------------------
    terr = sheets.entries("tiles")
    h.append("enum { " + ", ".join("T_%s" % cname(e.name) for e in terr) + ", T_COUNT };")
    h.append("extern const uint8_t *const bm_terrain_tiles[4];\nextern const int bm_terrain_tile_count[4];")
    h.append("extern const uint16_t bm_terrain_pals[4][TERRAIN_PALS * 16];")
    h.append("extern const uint16_t bm_terrain_meta[4][T_COUNT][4];\n")
    metas, pals, counts = [], [], []
    for s in range(4):
        cells = [frames_of(img["tiles"], e, s)[0] for e in terr]
        r = rsasset.convert_bg(cells, TERRAIN_PALS, pal_base=1, tile_base=0)
        if len(r.tiles) > PROPS_TILE_BASE:
            sys.exit("terrain of season %d needs %d tiles (max %d)" % (s, len(r.tiles), PROPS_TILE_BASE))
        c.append(rsasset.c_bytes("terrain_tiles_%d" % s, rsasset.tiles_bytes(r.tiles), static=True))
        counts.append(len(r.tiles))
        p = []
        for i in range(TERRAIN_PALS):
            p += rsasset.palette16(r.palettes[i] if i < len(r.palettes) else [])
        pals.append(p)
        metas.append(r.metas)
    c.append("const uint8_t *const bm_terrain_tiles[4] = {terrain_tiles_0, terrain_tiles_1, terrain_tiles_2, terrain_tiles_3};")
    c.append("const int bm_terrain_tile_count[4] = {%s};" % ", ".join(map(str, counts)))
    c.append("const uint16_t bm_terrain_pals[4][TERRAIN_PALS * 16] = {\n" +
             ",\n".join("    {" + ", ".join("0x%04x" % v for v in p) + "}" for p in pals) + "};")
    c.append("const uint16_t bm_terrain_meta[4][T_COUNT][4] = {\n" + ",\n".join(
        "    {" + ", ".join("{" + ", ".join("0x%04x" % v for v in m) + "}" for m in ms) + "}" for ms in metas) + "};\n")

    # ---- BG groups from items_fx: explosions and HUD ------------------------------------------
    for group, prefix, pal, base, sheet in (("fx", "FX", PAL_FX, FX_TILE_BASE, "items_fx"),
                                            ("hud", "HUD", PAL_HUD, HUD_TILE_BASE, "items_fx"),
                                            ("propbg", "PB", PAL_PROPS, PROPS_TILE_BASE, "props")):
        ents = [e for e in sheets.entries(sheet) if e.group == group]
        cells, names, idx = [], [], 0
        for e in ents:
            names.append("%s_%s = %d" % (prefix, cname(e.name.replace("expl_", "").replace("hud_", "")), idx))
            cells += frames_of(img[sheet], e)
            idx += e.frames
        r = rsasset.convert_bg(cells, 1, pal_base=pal, tile_base=base)
        h.append("enum { %s, %s_COUNT = %d };" % (", ".join(names), prefix, idx))
        h.append("extern const uint8_t bm_%s_tiles[];\nextern const int bm_%s_tile_count;" % (group, group))
        h.append("extern const uint16_t bm_%s_pal[16];\nextern const uint16_t bm_%s_meta[%s_COUNT][4];\n" %
                 (group, group, prefix))
        c.append(rsasset.c_bytes("bm_%s_tiles" % group, rsasset.tiles_bytes(r.tiles)))
        c.append("const int bm_%s_tile_count = %d;" % (group, len(r.tiles)))
        c.append(rsasset.c_u16("bm_%s_pal" % group, rsasset.palette16(r.palettes[0])))
        c.append("const uint16_t bm_%s_meta[%s_COUNT][4] = {\n" % (group, prefix) + ",\n".join(
            "    {" + ", ".join("0x%04x" % v for v in m) + "}" for m in r.metas) + "};\n")

    # ---- sprites ------------------------------------------------------------------------------
    # Base sprites share one tile block (always in VRAM). Each boss has its
    # own block + palette, loaded into the boss slot / OBJ palette 3 per level.
    sprite_entries = [e for e in sheets.ENTRIES if e.group in OBJ_GROUPS or e.group in BOSSES]
    tiles, defs, obj_pals, names = [], {}, [], []
    boss_tiles, boss_pals = [], []
    variant_base = {}
    for g in OBJ_GROUPS + BOSSES:
        ents = [e for e in sprite_entries if e.group == g]
        frames = []
        for e in ents:
            frames += frames_of(img[e.sheet], e)
        if not frames:                          # "boss" slot of the base palettes: filled per level
            obj_pals += [0] * 16
            continue
        r = rsasset.convert_obj(frames)
        if g in ("ferret", "cat"):          # base palettes of the palette-swap variants
            cnt = [0] * len(r.palette)
            for t in r.tiles:
                for v in t:
                    if v:
                        cnt[v - 1] += 1
            variant_base[g] = (r.palette, cnt)
        if g in BOSSES:
            block, pal, base = BOSSES.index(g) + 1, 3, 0
            boss_tiles.append(r.tiles)
            boss_pals.append(rsasset.palette16(r.palette))
        else:
            block, pal, base = 0, OBJ_GROUPS.index(g), len(tiles)
            obj_pals += rsasset.palette16(r.palette)
        k = 0
        for e in ents:
            defs[e.name] = []
            for f in range(e.frames):
                first, w, hh = r.frames[k]
                defs[e.name].append((base + first, w, hh, pal, block))
                k += 1
        if g not in BOSSES:
            tiles += r.tiles
    spr_rows, idx = [], 0
    for e in sprite_entries:
        names.append("SPR_%s = %d" % (cname(e.name), idx))
        for d in defs[e.name]:
            spr_rows.append("    {%d, %d, %d, %d, %d}" % d)
            idx += 1
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(names), idx))
    h.append("enum { " + ", ".join("OBJ_PAL_%s" % cname(g) for g in OBJ_GROUPS) + " };")
    h.append("enum { BOSS_NONE, " + ", ".join(cname(b) for b in BOSSES) + ", BOSS_KINDS };")
    h.append("typedef struct bm_sprite_def { uint16_t tile; uint8_t w, h, pal, block; } bm_sprite_def;")
    h.append("extern const bm_sprite_def bm_spr[SPR_COUNT];")
    h.append("extern const uint8_t bm_obj_tiles[];\nextern const int bm_obj_tile_count;")
    h.append("extern const uint16_t bm_obj_pals[%d];" % len(obj_pals))
    h.append("extern const uint8_t *const bm_boss_tiles[BOSS_KINDS];\nextern const int bm_boss_tile_count[BOSS_KINDS];")
    h.append("extern const uint16_t bm_boss_pals[BOSS_KINDS][16];\n")
    c.append("const bm_sprite_def bm_spr[SPR_COUNT] = {\n" + ",\n".join(spr_rows) + "};")
    c.append(rsasset.c_bytes("bm_obj_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int bm_obj_tile_count = %d;" % len(tiles))
    c.append(rsasset.c_u16("bm_obj_pals", obj_pals))
    for i, bt in enumerate(boss_tiles):
        c.append(rsasset.c_bytes("boss_tiles_%d" % i, rsasset.tiles_bytes(bt), static=True))
    c.append("const uint8_t *const bm_boss_tiles[BOSS_KINDS] = {0, %s};" %
             ", ".join("boss_tiles_%d" % i for i in range(len(boss_tiles))))
    c.append("const int bm_boss_tile_count[BOSS_KINDS] = {0, %s};" % ", ".join(str(len(b)) for b in boss_tiles))
    c.append("const uint16_t bm_boss_pals[BOSS_KINDS][16] = {{0}, %s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in p) + "}" for p in boss_pals))

    # ---- palette-swap enemy variants (one palette each, from the base sprite's ramps) ------------
    vnames, vpals = [], []
    for name, group, target, light in palette_variants.VARIANTS:
        pal, cnt = variant_base[group]
        vnames.append("VAR_%s" % cname(name))
        vpals.append(rsasset.palette16(palette_variants.variant_palette(pal, cnt, target, light)))
    h.append("enum { %s, VAR_COUNT };" % ", ".join(vnames))
    h.append("extern const uint16_t bm_variant_pals[VAR_COUNT][16];\n")
    c.append("const uint16_t bm_variant_pals[VAR_COUNT][16] = {\n" + ",\n".join(
        "    {" + ", ".join("0x%04x" % v for v in p) + "}" for p in vpals) + "};")

    # ---- title logo (art/title_logo.png, 256x64): BG tiles + map, one palette ------------------
    logo_path = os.path.join(a.art, "title_logo.png")
    h.append("#define LOGO_TILE_BASE 640\n#define LOGO_W 32\n#define LOGO_H 8")
    h.append("extern const uint8_t bm_logo_tiles[];\nextern const int bm_logo_tile_count;")
    h.append("extern const uint16_t bm_logo_pal[16];\nextern const uint16_t bm_logo_map[LOGO_W * LOGO_H];\n")
    if os.path.exists(logo_path):
        limg = rsasset.load(logo_path)
        cells = [rsasset.cell(limg, x * 8, y * 8, 8, 8) for y in range(8) for x in range(32)]
        r = rsasset.convert_bg(cells, 1, pal_base=5, tile_base=640)
        c.append(rsasset.c_bytes("bm_logo_tiles", rsasset.tiles_bytes(r.tiles)))
        c.append("const int bm_logo_tile_count = %d;" % len(r.tiles))
        c.append(rsasset.c_u16("bm_logo_pal", rsasset.palette16(r.palettes[0])))
        c.append(rsasset.c_u16("bm_logo_map", [m[0] for m in r.metas]))
    else:
        c.append("const uint8_t bm_logo_tiles[1];\nconst int bm_logo_tile_count = 0;")
        c.append("const uint16_t bm_logo_pal[16];\nconst uint16_t bm_logo_map[LOGO_W * LOGO_H];")

    # ---- asset pack: levels and music -------------------------------------------------------
    music_dir = os.path.join(a.out, "music")
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    pack = []
    for p in sorted(glob.glob(os.path.join(GAME, "levels", "*.txt"))):
        pack.append(("levels/" + os.path.basename(p), p))
    for p in sorted(glob.glob(os.path.join(music_dir, "*.mod"))):
        pack.append(("music/" + os.path.basename(p), p))
    entries = []
    for i, (name, path) in enumerate(pack):
        data = open(path, "rb").read()
        c.append(rsasset.c_bytes("pack_%d" % i, data, static=True))
        entries.append('    {"%s", pack_%d, %d}' % (name, i, len(data)))
    c.append("const rs_asset_entry bm_assets[] = {\n" + ",\n".join(entries) + ",\n    {0, 0, 0}};")
    h.append("extern const rs_asset_entry bm_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: %d obj tiles, terrain %s tiles, %d pack files -> %s" %
          (len(tiles), counts, len(pack), a.out))


if __name__ == "__main__":
    main()
