#!/usr/bin/env python3
"""Pogo Mamie asset build: the code-drawn sheets -> tiles, palettes, maps, sprites; the music ->
build/gen/pogomamie/assets.c + assets.h.

    build_assets.py --out build/gen/pogomamie [--art games/pogomamie/art] [--tileset IGNORED]

Every pixel is mapped to its palette index EXACTLY (the palettes of pm_sheets.py, in their order): the C code
recolours the BG palettes per district and at night, and the tests rely on the tiles' shapes.
MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft): games/pogomamie/LICENSE.
"""
import argparse
import glob
import os
import subprocess
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
import pm_sheets as S  # noqa: E402
import rsasset  # noqa: E402

# VRAM (absolute tile numbers). BG1: the house kit (font, panel font, 2x cache, panel frame: 0..296) and the logo
# it draws at run time (LOGO_TILE.., ~150 tiles for POGO MAMIE); BG4: two slots; OBJ: our sprites, then the kit's.
VR_BG1, VR_BG2, VR_BG3, VR_BG4, VR_OBJ = 0, 640, 768, 1024, 1536
LOGO_TILE = 320
PAL_UI, PAL_LOGO = 0, 5
FAR_SLOT = 256                  # tiles per BG4 slot (district & 1)


def to_index(img, x0, y0, w, h, pal, base=1):
    """w x h pixels -> palette indices (0 transparent); every opaque colour must be in pal (RGB list)."""
    px = img.load()
    lut = {rsasset.to555(c): i + base for i, c in enumerate(pal)}
    out = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b = px[x0 + x, y0 + y][:3]
            if (r, g, b) == S.MAGENTA:
                row.append(0)
            else:
                k = rsasset.to555((r, g, b))
                if k not in lut:
                    raise SystemExit("colour %s at (%d,%d) is not in the palette" % ((r, g, b), x0 + x, y0 + y))
                row.append(lut[k])
        out.append(row)
    return out


def tiles_of(cell):
    """a cell of indices -> 8x8 tiles (lists of 64), row-major"""
    h, w = len(cell), len(cell[0])
    return [[cell[ty + y][tx + x] for y in range(8) for x in range(8)] for ty in range(0, h, 8) for tx in range(0, w, 8)]


def hflip(t):
    return [t[y * 8 + 7 - x] for y in range(8) for x in range(8)]


def vflip(t):
    return [t[(7 - y) * 8 + x] for y in range(8) for x in range(8)]


def bg_map(cell, pal_no, tile_base, tiles, index):
    """A panorama -> map entries, adding new tiles (deduplicated, flips too) to `tiles`."""
    h, w = len(cell), len(cell[0])
    out = []
    for ty in range(0, h, 8):
        for tx in range(0, w, 8):
            t = [cell[ty + y][tx + x] for y in range(8) for x in range(8)]
            if not any(t):
                out.append(0)
                continue
            hit = None
            for hf, vf, f in ((0, 0, lambda v: v), (1, 0, hflip), (0, 1, vflip), (1, 1, lambda v: vflip(hflip(v)))):
                k = tuple(f(t))
                if k in index:
                    hit = (index[k], hf, vf)
                    break
            if hit is None:
                tiles.append(t)
                index[tuple(t)] = len(tiles) - 1
                hit = (len(tiles) - 1, 0, 0)
            out.append(rsasset.rs_map(tile_base + hit[0], pal_no, 0, hit[1], hit[2]))
    return out


def pal555(pal):
    return [rsasset.to555(c) for _, c in pal]


def carr(ctype, name, data, fmt="0x%04x", per=16):
    s = ["const %s %s[%d] = {" % (ctype, name, len(data))]
    for i in range(0, len(data), per):
        s.append("    " + ", ".join(fmt % v for v in data[i:i + per]) + ",")
    s.append("};")
    return "\n".join(s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    ap.add_argument("--tileset", default="", help="ignored (the tiles are code-drawn)")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    c = ["/* Generated by games/pogomamie/tools/build_assets.py from %s. Do not edit. */" % os.path.relpath(a.art, ROOT),
         '#include "assets.h"\n']
    h = ["/* Generated by games/pogomamie/tools/build_assets.py. Do not edit. */",
         "#ifndef PM_ASSETS_H\n#define PM_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n",
         "#define VR_BG1 %d\n#define VR_BG2 %d\n#define VR_BG3 %d\n#define VR_BG4 %d\n#define VR_OBJ %d" %
         (VR_BG1, VR_BG2, VR_BG3, VR_BG4, VR_OBJ),
         "#define LOGO_TILE %d\n#define FAR_SLOT %d\n#define PAL_UI %d\n#define PAL_LOGO %d" %
         (LOGO_TILE, FAR_SLOT, PAL_UI, PAL_LOGO)]
    for name, i in S.BG_PAL_INDEX.items():
        h.append("#define PAL_%s %d" % (name.upper(), i))
    stats = []

    # ---- BG palettes (base colours; the C code tints them) -------------------------------------------------------
    bgp = [[0] * 16 for _ in range(8)]
    for name, i in S.BG_PAL_INDEX.items():
        bgp[i] = rsasset.palette16(pal555(S.BG_PALS[name]))
    c.append("const uint16_t pm_bg_pal[8][16] = {%s};" % ", ".join("{" + ", ".join("0x%04x" % v for v in p) + "}"
                                                                   for p in bgp))
    h.append("extern const uint16_t pm_bg_pal[8][16];")
    c.append("const rs_color pm_logo_ramps[2][3] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % rsasset.to555(col) for col in r) + "}" for r in S.LOGO_RAMPS))
    h.append("extern const rs_color pm_logo_ramps[2][3];   /* the title logo's word ramps (house_ui.c hu_logo) */")
    for name in ("mid", "far"):
        for i, (cn, _) in enumerate(S.BG_PALS[name]):
            h.append("#define C_%s %d" % (cn.upper(), i + 1))
    for name in ("roof", "stone", "house"):
        for i, (cn, _) in enumerate(S.BG_PALS[name]):
            if cn.startswith("glass"):
                h.append("#define C_%s_%s %d" % (name.upper(), cn.upper(), i + 1))

    # ---- BG2 tiles ----------------------------------------------------------------------------------------------
    im = Image.open(os.path.join(a.art, "tiles", "bg2.png")).convert("RGB")
    bg2, names, pals, tops, flags = [], [], [], [], []
    for i, (name, pal) in enumerate(S.BG_TILES):
        cell = to_index(im, (i % 16) * 8, (i // 16) * 8, 8, 8, [c2 for _, c2 in S.BG_PALS[pal]])
        t = [v for row in cell for v in row]
        bg2.append(t)
        names.append("T_%s = %d" % (name.upper(), i))
        pals.append(S.BG_PAL_INDEX[pal])
        for x in range(8):
            col = [t[y * 8 + x] for y in range(8)]
            tops.append(next((y for y, v in enumerate(col) if v), 8))
        flags.append((1 if name not in S.BG_TILE_NONSOLID else 0) | (2 if name in S.BG_TILE_GROUND else 0) |
                     (4 if name in S.BG_TILE_GLASS else 0) | (8 if name in S.BG_TILE_BUMP else 0) |
                     (16 if name in S.BG_TILE_OPEN else 0))
    h.append("enum { %s, T_COUNT = %d };" % (", ".join(names), len(bg2)))
    h.append("#define TF_SOLID 1\n#define TF_GROUND 2\n#define TF_GLASS 4\n#define TF_BUMP 8\n#define TF_OPEN 16")
    c.append(rsasset.c_bytes("pm_bg2_tiles", rsasset.tiles_bytes(bg2)))
    c.append(carr("uint8_t", "pm_bg2_pal", pals, "%d"))
    c.append(carr("uint8_t", "pm_tile_top", tops, "%d"))
    c.append(carr("uint8_t", "pm_tile_flags", flags, "%d"))
    h.append("extern const uint8_t pm_bg2_tiles[];\nextern const uint8_t pm_bg2_pal[T_COUNT];")
    h.append("extern const uint8_t pm_tile_top[T_COUNT * 8];   /* first opaque row of each column (8 = none) */")
    h.append("extern const uint8_t pm_tile_flags[T_COUNT];")
    stats.append("BG2 %d" % len(bg2))

    # ---- BG3: the mid-ground -----------------------------------------------------------------------------------
    im = Image.open(os.path.join(a.art, "tiles", "mid.png")).convert("RGB")
    cell = to_index(im, 0, 0, S.MID_W, S.MID_H, [c2 for _, c2 in S.BG_PALS["mid"]])
    tiles = [[0] * 64]
    mp = bg_map(cell, S.BG_PAL_INDEX["mid"], 0, tiles, {tuple([0] * 64): 0})
    c.append(rsasset.c_bytes("pm_mid_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int pm_mid_tile_count = %d;" % len(tiles))
    c.append(carr("uint16_t", "pm_mid_map", mp))
    h.append("#define MID_W 64\n#define MID_H %d\n#define MID_Y %d" % (S.MID_H // 8, S.MID_Y // 8))
    h.append("extern const uint8_t pm_mid_tiles[];\nextern const int pm_mid_tile_count;\n"
             "extern const uint16_t pm_mid_map[MID_W * MID_H];")
    stats.append("BG3 %d" % len(tiles))

    # ---- BG4: the four district backdrops, each in its slot (district & 1) --------------------------------------
    far_counts = []
    for d, name in enumerate(S.DISTRICTS):
        im = Image.open(os.path.join(a.art, "tiles", "far_%s.png" % name)).convert("RGB")
        cell = to_index(im, 0, 0, S.FAR_W, S.FAR_H, [c2 for _, c2 in S.BG_PALS["far"]])
        tiles = [[0] * 64]
        mp = bg_map(cell, S.BG_PAL_INDEX["far"], (d & 1) * FAR_SLOT, tiles, {tuple([0] * 64): 0})
        if len(tiles) > FAR_SLOT:
            raise SystemExit("far_%s: %d tiles > %d" % (name, len(tiles), FAR_SLOT))
        c.append(rsasset.c_bytes("pm_far%d_tiles" % d, rsasset.tiles_bytes(tiles)))
        c.append(carr("uint16_t", "pm_far%d_map" % d, mp))
        far_counts.append(len(tiles))
    c.append("const uint8_t *const pm_far_tiles[4] = {pm_far0_tiles, pm_far1_tiles, pm_far2_tiles, pm_far3_tiles};")
    c.append("const uint16_t *const pm_far_map[4] = {pm_far0_map, pm_far1_map, pm_far2_map, pm_far3_map};")
    c.append("const int pm_far_tile_count[4] = {%s};" % ", ".join(str(n) for n in far_counts))
    h.append("#define FAR_W 64\n#define FAR_H %d\n#define FAR_Y %d" % (S.FAR_H // 8, S.FAR_Y // 8))
    h.append("extern const uint8_t *const pm_far_tiles[4];\nextern const uint16_t *const pm_far_map[4];\n"
             "extern const int pm_far_tile_count[4];")
    stats.append("BG4 %s" % "+".join(str(n) for n in far_counts))

    # ---- sprites -----------------------------------------------------------------------------------------------
    im = Image.open(os.path.join(a.art, "sprites.png")).convert("RGB")
    tiles, rows, enum, surf = [], [], [], []
    obj_pals = [0] * 128
    for pname, pi in S.OBJ_PAL_INDEX.items():
        if pname in S.PLAYER_PALS:          # the family: Mamie's palette recoloured
            base = dict(S.OBJ_PALS["mamie"])
            base.update(S.PLAYER_PALS[pname])
            obj_pals[pi * 16:pi * 16 + 16] = rsasset.palette16([rsasset.to555(base[n]) for n, _ in S.OBJ_PALS["mamie"]])
        else:
            obj_pals[pi * 16:pi * 16 + 16] = rsasset.palette16(pal555(S.OBJ_PALS[pname]))
    idx = 0
    head = []
    for s in S.SPRITES:
        pal = [c2 for _, c2 in S.OBJ_PALS[s.pal]]
        enum.append("SPR_%s = %d" % (s.name.upper(), idx))
        if s.surface >= 0:
            surf.append("#define SURF_%s %d" % (s.name.upper(), s.surface))
        for (x, y, w, hh) in S.frame_rects(s.name):
            cell = to_index(im, x, y, w, hh, pal)
            rows.append("{%d, %d, %d, %d}" % (len(tiles), w, hh, S.OBJ_PAL_INDEX[s.pal]))
            tiles += tiles_of(cell)
            idx += 1
            if s.name == "mamie":           # Papi's overlay position: from the headscarf's top
                sc = [pal.index(S.OBJ_PALS["mamie"][3][1]) + 1, pal.index(S.OBJ_PALS["mamie"][4][1]) + 1]
                pts = [(xx, yy) for yy in range(hh) for xx in range(w) if cell[yy][xx] in sc]
                top = min(p[1] for p in pts)
                xs = [p[0] for p in pts if p[1] <= top + 1]
                cx = (min(xs) + max(xs)) // 2
                head.append("{%d, %d}" % (cx + 1 - 8, top - 5))
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(enum), idx))
    h.append("enum { %s };" % ", ".join("MF_%s" % f.upper() for f in S.MAMIE_FRAMES))
    h += surf
    h.append("typedef struct pm_sprite_def { uint16_t tile; uint8_t w, h, pal; } pm_sprite_def;")
    h.append("extern const pm_sprite_def pm_spr[SPR_COUNT];")
    h.append("extern const int8_t pm_papi_head[%d][2];   /* Papi's beret overlay in each of Mamie's frames */" %
             len(head))
    h.append("extern const uint8_t pm_obj_tiles[];\nextern const int pm_obj_tile_count;\nextern const uint16_t pm_obj_pals[128];")
    c.append("const pm_sprite_def pm_spr[SPR_COUNT] = {\n    " + ",\n    ".join(rows) + "};")
    c.append("const int8_t pm_papi_head[%d][2] = {%s};" % (len(head), ", ".join(head)))
    c.append(rsasset.c_bytes("pm_obj_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int pm_obj_tile_count = %d;" % len(tiles))
    c.append(rsasset.c_u16("pm_obj_pals", obj_pals))
    stats.append("OBJ %d" % len(tiles))

    # ---- asset pack: the music ------------------------------------------------------------------------------------
    music_dir = os.path.join(a.out, "music")
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    pack = [("music/" + os.path.basename(p), p) for p in sorted(glob.glob(os.path.join(music_dir, "*.mod")))]
    entries = []
    for i, (name, path) in enumerate(pack):
        data = open(path, "rb").read()
        c.append(rsasset.c_bytes("pack_%d" % i, data, static=True))
        entries.append('    {"%s", pack_%d, %d}' % (name, i, len(data)))
    c.append("const rs_asset_entry pm_assets[] = {\n" + ",\n".join(entries) + ",\n    {0, 0, 0}};")
    h.append("extern const rs_asset_entry pm_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: tiles %s, %d pack files -> %s" % (", ".join(stats), len(pack), a.out))


if __name__ == "__main__":
    main()
