#!/usr/bin/env python3
"""Tests of the review tool's TODO.md writing (tools/art_review.py): a button
changes only its row's Status and Notes, every other byte is kept, a
concurrent edit by the image agent (between our read and our write) is not
lost, the write is atomic with a backup, the batch validation touches only
unflagged GENERATED rows of one family, and the HTTP API works end to end.
MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft).
"""
import json
import os
import sys
import tempfile
import threading
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
import art_review as ar  # noqa: E402

failures = 0

TODO = """# Bomber Mole art TODO

Rules: edit only | Status | and | Notes |.

| ID | Status | Sheet | Frame size | Frames | Description / prompt | Notes |
|---|---|---|---|---|---|---|
| mole_walk_down | GENERATED | characters.png | 16x16 | 3 | The mole walking toward the viewer. 3 frames. | from first-batch sheet |
| mole_walk_up | GENERATED | characters.png | 16x16 | 3 | The mole walking away. |  |
| mole_hurt | GENERATED | characters.png | 16x16 | 1 | The mole hurt. |  |
| ferret_walk_down | GENERATED | characters.png | 16x16 | 2 | The ferret. |  |
| bomb | TODO | items_fx.png | 16x16 | 3 | A bomb. |  |
"""


def check(cond, msg):
    global failures
    print(("  ok   " if cond else "  FAIL ") + msg)
    failures += 0 if cond else 1


def lines(p):
    with open(p, "rb") as f:
        return f.read().decode("utf-8").splitlines(keepends=True)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        inc = os.path.join(tmp, "incoming")
        os.makedirs(inc)
        todo = os.path.join(inc, "TODO.md")
        bak = os.path.join(tmp, "backups")
        with open(todo, "wb") as f:
            f.write(TODO.replace("\n", "\r\n", 3).encode("utf-8"))      # mixed line endings are kept
        before = lines(todo)

        # 1. one row, only Status and Notes
        ar.update_rows(todo, lambda rows: ar.action_changes(rows, "mole_walk_up", "reject", "ears too big | fix", True), bak)
        after = lines(todo)
        diff = [i for i, (a, b) in enumerate(zip(before, after)) if a != b]
        check(len(before) == len(after) and len(diff) == 1, "only one line changed (%s)" % diff)
        row = after[diff[0]]
        check(row == "| mole_walk_up | REJECTED | characters.png | 16x16 | 3 | The mole walking away. | "
                     "Owner: ears too big / fix |\n", "that row: Status and Notes only (%r)" % row)
        check(after[0].endswith("\r\n") and after[-1].endswith("\n"), "line endings kept")
        check(os.listdir(bak) and not [n for n in os.listdir(inc) if n.endswith(".tmp")],
              "backup written, no temporary file left")
        rows = ar.parse_rows("".join(after))
        check(rows["mole_walk_down"]["notes"] == "from first-batch sheet", "other rows' notes untouched")

        # 2. validate keeps the notes and adds the owner's; reset restores GENERATED (or TODO without a PNG)
        ar.update_rows(todo, lambda rows: ar.action_changes(rows, "mole_walk_down", "validate", "", True), bak)
        rows = ar.parse_rows("".join(lines(todo)))
        check(rows["mole_walk_down"] == {"status": "VALIDATED", "notes": "from first-batch sheet"}, "validate")
        ar.update_rows(todo, lambda rows: ar.action_changes(rows, "mole_walk_down", "reset", "", True), bak)
        ar.update_rows(todo, lambda rows: ar.action_changes(rows, "bomb", "reset", "", False), bak)
        rows = ar.parse_rows("".join(lines(todo)))
        check(rows["mole_walk_down"]["status"] == "GENERATED" and rows["bomb"]["status"] == "TODO", "reset")

        # 3. the image agent writes between our read and our write: its edit is not lost
        calls = []

        def agent():
            if calls:
                return
            calls.append(1)
            text = "".join(lines(todo)).replace("| bomb | TODO |", "| bomb | GENERATED |")
            text = text.replace("| A bomb. |  |", "| A bomb. | regenerated by the agent |")
            with open(todo, "wb") as f:
                f.write(text.encode("utf-8"))
        ar.update_rows(todo, lambda rows: ar.action_changes(rows, "mole_hurt", "validate", "nice", True), bak,
                       _before_replace=agent)
        rows = ar.parse_rows("".join(lines(todo)))
        check(rows["bomb"] == {"status": "GENERATED", "notes": "regenerated by the agent"},
              "the concurrent edit of another row survives")
        check(rows["mole_hurt"] == {"status": "VALIDATED", "notes": "Owner: nice"}, "and ours is applied")

        # 4. unknown row: an error, the file is untouched
        snap = lines(todo)
        try:
            ar.update_rows(todo, lambda rows: ar.action_changes(rows, "nope", "validate", "", True), bak)
            check(False, "unknown row raises")
        except KeyError:
            check(lines(todo) == snap, "unknown row: nothing written")

        # 5. batch: only GENERATED + unflagged + imported rows of that family
        rv = ar.Review(inc, os.path.join(tmp, "cache"), 24)
        rv.index = {"mole_walk_up": {"family": "mole", "imported": True, "flags": [], "frame_flags": []},
                    "mole_walk_down": {"family": "mole", "imported": True, "flags": [], "frame_flags": []},
                    "mole_hurt": {"family": "mole", "imported": True, "flags": [], "frame_flags": []},
                    "ferret_walk_down": {"family": "ferret", "imported": True, "flags": [], "frame_flags": []}}
        rv.index["mole_walk_down"]["frame_flags"] = ["frame 1: jitter"]
        ids = rv.unflagged("mole", ar.parse_rows("".join(lines(todo))))
        check(ids == [], "batch: flagged, rejected and validated rows are skipped (%s)" % ids)

        # 6. HTTP end to end on a free port
        rv.stamp = 1
        with open(os.path.join(inc, "ferret_walk_down.png"), "wb") as f:
            f.write(b"\x89PNG")
        srv = ar.http.server.ThreadingHTTPServer(("127.0.0.1", 0), ar.make_handler(rv))
        th = threading.Thread(target=srv.serve_forever, daemon=True)
        th.start()
        base = "http://127.0.0.1:%d" % srv.server_address[1]

        def post(path, body):
            req = urllib.request.Request(base + path, data=json.dumps(body).encode(), method="POST")
            try:
                with urllib.request.urlopen(req) as r:
                    return json.loads(r.read())
            except urllib.error.HTTPError as ex:
                return json.loads(ex.read())
        st = json.loads(urllib.request.urlopen(base + "/api/state").read())
        check(len(st["rows"]) == 5 and urllib.request.urlopen(base + "/").status == 200, "GET / and /api/state")
        j = post("/api/batch", {"family": "ferret"})
        check(j.get("changed") == ["ferret_walk_down"], "POST /api/batch validates the unflagged ferret (%s)" % j)
        j = post("/api/set", {"id": "mole_walk_up", "action": "validate", "note": ""})
        rows = ar.parse_rows("".join(lines(todo)))
        check(j.get("ok") and rows["mole_walk_up"]["status"] == "VALIDATED" and
              rows["ferret_walk_down"]["status"] == "VALIDATED", "POST /api/set")
        j = post("/api/set", {"id": "../TODO", "action": "validate"})
        check("error" in j, "bad ids are refused")
        srv.shutdown()
    print("art_review: %s" % ("all passed" if not failures else "%d FAILED" % failures))
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
