#!/usr/bin/env python3
"""Duck Parade asset build: the code-drawn sheets (make_art.py) -> tiles, palettes, metatiles and sprites;
the music (make_music.py: the march module and the layers the game adds) -> build/gen/duckparade/assets.c + .h

    build_assets.py --out build/gen/duckparade [--art games/duckparade/art] [--tileset IGNORED]

VRAM (absolute tiles): BG1 (the house kit, the logo) 0; BG3 the field 1024; BG2 the cloud shadows and BG4 the
sky's clouds share 1536; OBJ 3072 (our sprites, then the kit's at KIT_OBJ_TILE).
BG palettes: 0 UI (kit), 1 grass, 2 road, 3 rapids, 4 railway and park, 5 the logo (kit), 6 ponds, 7 clouds.
OBJ palettes: 0 Mother Duck, 1 Father Duck, 4 the buff duck, 5 the blue duck (players 1-4: the same tiles), 2
ducklings and effects, 3 the kit (and the egg medals), 6 cars A, 7 the rest of the world (cars B, river things, the
train, the lights and the fox).

MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft): games/duckparade/LICENSE.
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "games", "common", "tools"))
import rsasset  # noqa: E402
import make_art  # noqa: E402
import make_music  # noqa: E402

VR_BG1, VR_FIELD, VR_FAR, VR_OBJ = 0, 1024, 1536, 3072
KIT_OBJ_TILE = 880


def cells8(img, x0, y0, w, h):
    return [rsasset.cell(img, x0 + x * 8, y0 + y * 8, 8, 8) for y in range(h // 8) for x in range(w // 8)]


def arr(name, data, ctype="uint16_t", fmt="0x%04x"):
    return "const %s %s[%d] = {%s};" % (ctype, name, len(data), ", ".join(fmt % v for v in data))


def cname(s):
    return s.upper()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    ap.add_argument("--tileset", default="", help="ignored (the tiles are code-drawn)")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    if not os.path.exists(os.path.join(a.art, "sprites.png")):
        make_art.write_all(a.art)
    c = ["/* Generated by games/duckparade/tools/build_assets.py. Do not edit. */", '#include "assets.h"\n']
    h = ["/* Generated by games/duckparade/tools/build_assets.py. Do not edit. */",
         "#ifndef DP_ASSETS_H\n#define DP_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n",
         "#define VR_BG1 %d\n#define VR_FIELD %d\n#define VR_FAR %d\n#define VR_OBJ %d\n#define KIT_OBJ_TILE %d" %
         (VR_BG1, VR_FIELD, VR_FAR, VR_OBJ, KIT_OBJ_TILE),
         "#define PAL_GRASS %d\n#define PAL_ROAD %d\n#define PAL_WATER %d\n#define PAL_RAIL %d\n#define PAL_LOGO %d\n"
         "#define PAL_POND %d\n#define PAL_CLOUD %d" % (make_art.META_PAL["grass"], make_art.META_PAL["road"],
                                                       make_art.META_PAL["water"], make_art.META_PAL["rail"],
                                                       make_art.PAL_LOGO, make_art.META_PAL["pond"], make_art.PAL_CLOUD)]
    stats = []
    bg_pals = [[0] * 16 for _ in range(8)]

    # ---- the field (BG3): metatiles per palette group, then the rapids' windows -----------------------------
    field = rsasset.load(os.path.join(a.art, "tiles", "field.png"))
    _, names = make_art.field_image()
    metas = make_art.metas()
    tiles = [[0] * 64]
    meta_rows = {}
    for group, pal in sorted(make_art.META_PAL.items(), key=lambda kv: kv[1]):
        if group == "water":
            continue
        gnames = [n for n in names if metas[n][1] == group]
        cells = []
        for n in gnames:
            i = names.index(n)
            cells.append(rsasset.cell(field, (i % 16) * 16, (i // 16) * 16, 16, 16))
        r = rsasset.convert_bg(cells, 1, pal_base=pal, tile_base=len(tiles), reserve_blank=False)
        tiles += r.tiles
        bg_pals[pal] = rsasset.palette16(r.palettes[0])
        for n, m in zip(gnames, r.metas):
            meta_rows[n] = m
    river = rsasset.load(os.path.join(a.art, "tiles", "river.png"))
    rcells, rkeys = [], []
    for s in range(16):
        for lb in (0, 1):
            for rb in (0, 1):
                rcells.append(rsasset.cell(river, s * 16, (lb * 2 + rb) * 16, 16, 16))
                rkeys.append((s, lb, rb))
    r = rsasset.convert_bg(rcells, 1, pal_base=make_art.META_PAL["water"], tile_base=len(tiles), reserve_blank=False)
    tiles += r.tiles
    bg_pals[make_art.META_PAL["water"]] = rsasset.palette16(r.palettes[0])
    river_meta = dict(zip(rkeys, r.metas))
    order = sorted(meta_rows)
    h.append("enum { %s, META_COUNT = %d };" % (", ".join("META_%s" % cname(n) for n in order), len(order)))
    h.append("extern const uint16_t dp_meta[META_COUNT][4];\nextern const uint16_t dp_river[16][2][2][4];")
    h.append("extern const uint8_t dp_field_tiles[];\nextern const int dp_field_tile_count;")
    c.append("const uint16_t dp_meta[META_COUNT][4] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in meta_rows[n]) + "}" for n in order))
    c.append("const uint16_t dp_river[16][2][2][4] = {%s};" % ", ".join(
        "{" + ", ".join("{" + ", ".join("{" + ", ".join("0x%04x" % v for v in river_meta[(s, lb, rb)]) + "}"
                                         for rb in (0, 1)) + "}" for lb in (0, 1)) + "}" for s in range(16)))
    c.append(rsasset.c_bytes("dp_field_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int dp_field_tile_count = %d;" % len(tiles))
    assert len(tiles) <= 512, "the field uses %d tiles" % len(tiles)
    stats.append("field %d" % len(tiles))

    # ---- the sky's clouds (BG4, 512x16) and the cloud shadows (BG2, 256x128): one tile set, palette 7 ---------------
    sky = rsasset.load(os.path.join(a.art, "tiles", "sky.png"))
    shd = rsasset.load(os.path.join(a.art, "tiles", "shadows.png"))
    far_cells = cells8(sky, 0, 0, 512, 16) + cells8(shd, 0, 0, 256, 128)
    r = rsasset.convert_bg(far_cells, 1, pal_base=make_art.PAL_CLOUD, tile_base=0)
    bg_pals[make_art.PAL_CLOUD] = rsasset.palette16(r.palettes[0])
    far_pal = r.palettes[0]
    h.append("#define SKY_IDX %d\n#define SHADOW_IDX %d" % (far_pal.index(rsasset.to555(make_art.SKY_KEY)) + 1,
                                                        far_pal.index(rsasset.to555(make_art.SHADOW_SUB)) + 1))
    sky_map = [m[0] for m in r.metas[:64 * 2]]
    shd_map = [m[0] for m in r.metas[64 * 2:]]
    c.append(rsasset.c_bytes("dp_far_tiles", rsasset.tiles_bytes(r.tiles)))
    c.append("const int dp_far_tile_count = %d;" % len(r.tiles))
    c.append(arr("dp_sky_map", sky_map))
    c.append(arr("dp_shadow_map", shd_map))
    h.append("extern const uint8_t dp_far_tiles[];\nextern const int dp_far_tile_count;")
    h.append("extern const uint16_t dp_sky_map[64 * 2];\nextern const uint16_t dp_shadow_map[32 * 16];")
    stats.append("far %d" % len(r.tiles))
    h.append("extern const uint16_t dp_bg_pals[8][16];")
    c.append("const uint16_t dp_bg_pals[8][16] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in p) + "}" for p in bg_pals))

    # ---- sprites ---------------------------------------------------------------------------------------------------
    sheet = rsasset.load(os.path.join(a.art, "sprites.png"))
    lay, _hh = make_art.layout()
    obj_tiles, rows, enum_names = [], [], []
    obj_pals = [0] * 128
    idx = 0
    for g in make_art.GROUPS:
        pal555 = [rsasset.to555(v) for v in make_art.PALETTES[g]]
        assert len(pal555) <= 15, g
        ents = [(e, x, y) for (e, x, y) in lay if e[4] == g]
        frames = []
        for (name, w, hh, n, _g, _fn), x, y in ents:
            frames += [rsasset.cell(sheet, x + k * w, y, w, hh) for k in range(n)]
        ro = rsasset.convert_obj(frames, palette=pal555)
        slot = make_art.OBJ_PAL[g]
        if g != "kit":
            obj_pals[slot * 16:slot * 16 + 16] = rsasset.palette16(pal555)
        if g == "duck":                            # the other parents: the same tiles (OBJ 1, 4, 5)
            for ps, cols in make_art.PLAYER_PALS.items():
                obj_pals[ps * 16:ps * 16 + 16] = rsasset.palette16([rsasset.to555(v) for v in cols])
        k = 0
        for (name, w, hh, n, _g, _fn), x, y in ents:
            enum_names.append("SPR_%s = %d" % (cname(name), idx))
            for f in range(n):
                first, fw, fh = ro.frames[k]
                rows.append("{%d, %d, %d, %d}" % (len(obj_tiles) + first, fw, fh, slot))
                k += 1
                idx += 1
        obj_tiles += ro.tiles
    assert len(obj_tiles) <= KIT_OBJ_TILE, "the sprites (%d tiles) overlap the kit's" % len(obj_tiles)
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(enum_names), idx))
    h.append("typedef struct dp_sprite_def { uint16_t tile; uint8_t w, h, pal; } dp_sprite_def;")
    h.append("extern const dp_sprite_def dp_spr[SPR_COUNT];")
    h.append("extern const uint8_t dp_obj_tiles[];\nextern const int dp_obj_tile_count;\nextern const uint16_t dp_obj_pals[128];")
    c.append("const dp_sprite_def dp_spr[SPR_COUNT] = {\n    " + ",\n    ".join(rows) + "};")
    c.append(rsasset.c_bytes("dp_obj_tiles", rsasset.tiles_bytes(obj_tiles)))
    c.append("const int dp_obj_tile_count = %d;" % len(obj_tiles))
    c.append(rsasset.c_u16("dp_obj_pals", obj_pals))
    stats.append("OBJ %d" % len(obj_tiles))

    # ---- the music: the march module and the layers the game plays on top ------------------------------------------
    music_dir = os.path.join(a.out, "music")
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    data = open(os.path.join(music_dir, "march.mod"), "rb").read()
    c.append(rsasset.c_bytes("pack_0", data, static=True))
    c.append('const rs_asset_entry dp_assets[] = {\n    {"music/march.mod", pack_0, %d},\n    {0, 0, 0}};' % len(data))
    lay_notes = make_music.layers()
    n_rows = len(lay_notes[0])
    h.append("#define LAYER_ROWS %d\n#define LAYER_COUNT %d" % (n_rows, len(lay_notes)))
    h.append("typedef struct dp_note { uint16_t pitch; uint8_t vol, pad; } dp_note;")
    h.append("extern const dp_note dp_layers[LAYER_COUNT][LAYER_ROWS];")
    c.append("const dp_note dp_layers[LAYER_COUNT][LAYER_ROWS] = {%s};" % ", ".join(
        "{" + ", ".join("{%d, %d, 0}" % (p, v) for p, v in L) + "}" for L in lay_notes))
    h.append("#define LAYER_TRUMPET_HZ %d\n#define LAYER_GLOCK_HZ %d" % (make_music.TRUMPET_HZ, make_music.GLOCK_HZ))
    h.append("extern const rs_asset_entry dp_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: tiles %s, music %d bytes, %d layer rows -> %s" % (", ".join(stats), len(data), n_rows, a.out))


if __name__ == "__main__":
    main()
