#!/usr/bin/env python3
"""@NAME@ asset build: the code-drawn sheets (make_art.py) -> tiles, palettes, maps and sprites; the music
(make_music.py) -> build/gen/@ID@/assets.c + assets.h.

    build_assets.py --out build/gen/@ID@ [--art games/@ID@/art] [--tileset IGNORED]

MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft): games/@ID@/LICENSE.
"""
import argparse
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "games", "common", "tools"))
import rsasset  # noqa: E402
import house_style as hs  # noqa: E402
import make_art  # noqa: E402

PAL_GROUND, PAL_HILLS, PAL_LOGO = 1, 2, 5
OBJ_PAL = {"hero": 0, "hero2": 1, "props": 2}           # OBJ 3: the house kit sprites
VR_BG1, VR_BG2, VR_BG3, VR_OBJ = 0, 1024, 1536, 3072
KIT_OBJ_TILE = 512                                        # the kit's sprites (house_ui.h HU_OBJ_TILES) after ours
# player 2: the hero's hue rotated (house_style.hue_swap); REPLACE the hue range with the hero's main colour's
P2_HUE = (0.80, 1.00, -0.45)                              # pinks -> blues


def cells8(img, x0, y0, w, h):
    return [rsasset.cell(img, x0 + x * 8, y0 + y * 8, 8, 8) for y in range(h // 8) for x in range(w // 8)]


def arr(name, data):
    return "const uint16_t %s[%d] = {%s};" % (name, len(data), ", ".join("0x%04x" % v for v in data))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    ap.add_argument("--tileset", default="", help="ignored (the tiles are code-drawn)")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    if not os.path.exists(os.path.join(a.art, "sprites.png")):
        make_art.write_all(a.art)
    c = ["/* Generated by games/@ID@/tools/build_assets.py. Do not edit. */", '#include "assets.h"\n']
    h = ["/* Generated by games/@ID@/tools/build_assets.py. Do not edit. */",
         "#ifndef GM_ASSETS_H\n#define GM_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n",
         "#define VR_BG1 %d\n#define VR_BG2 %d\n#define VR_BG3 %d\n#define VR_OBJ %d\n#define KIT_OBJ_TILE %d" %
         (VR_BG1, VR_BG2, VR_BG3, VR_OBJ, KIT_OBJ_TILE),
         "#define PAL_GROUND %d\n#define PAL_HILLS %d\n#define PAL_LOGO %d" % (PAL_GROUND, PAL_HILLS, PAL_LOGO)]
    stats = []

    # ---- BG2: the ground (512x48 at y 192), BG3: the hills (512x96 at y 96) --------------------------------------
    for layer, key, name, pal, y in (("bg2", "ground", "GROUND", PAL_GROUND, 192), ("bg3", "hills", "HILLS", PAL_HILLS, 96)):
        f, w, hh = make_art.PANORAMAS[key]
        img = rsasset.load(os.path.join(a.art, f))
        r = rsasset.convert_bg(cells8(img, 0, 0, w, hh), 1, pal_base=pal, tile_base=0)
        c.append(rsasset.c_bytes("gm_%s_tiles" % layer, rsasset.tiles_bytes(r.tiles)))
        c.append("const int gm_%s_tile_count = %d;" % (layer, len(r.tiles)))
        c.append(arr("gm_%s_map" % key, [m[0] for m in r.metas]))
        c.append(arr("gm_%s_pal" % key, rsasset.palette16(r.palettes[0])))
        h.append("#define %s_H %d\n#define %s_Y %d" % (name, hh // 8, name, y))
        h.append("extern const uint8_t gm_%s_tiles[];\nextern const int gm_%s_tile_count;" % (layer, layer))
        h.append("extern const uint16_t gm_%s_map[64 * %s_H];\nextern const uint16_t gm_%s_pal[16];" % (key, name, key))
        stats.append("%s %d" % (layer.upper(), len(r.tiles)))

    # ---- sprites ----------------------------------------------------------------------------------------------------
    sheet = rsasset.load(os.path.join(a.art, "sprites.png"))
    tiles, rows, names, pals = [], [], [], [0] * 48
    idx = 0
    for g in ("hero", "props"):
        ents = [e for e in make_art.SPRITES if e[6] == g]
        frames = []
        for name, x, y, w, hh, n, _g in ents:
            frames += [rsasset.cell(sheet, x + i * w, y, w, hh) for i in range(n)]
        ro = rsasset.convert_obj(frames)
        p16 = rsasset.palette16(ro.palette)
        pals[OBJ_PAL[g] * 16:OBJ_PAL[g] * 16 + 16] = p16
        if g == "hero":
            rgb = [rsasset.rgb888(v) for v in p16[1:]]
            pals[16:32] = [0] + [rsasset.to555(v) for v in hs.hue_swap(rgb, *P2_HUE)]
        k = 0
        for name, x, y, w, hh, n, _g in ents:
            names.append("SPR_%s = %d" % (name.upper(), idx))
            for f in range(n):
                first, fw, fh = ro.frames[k]
                rows.append("{%d, %d, %d, %d}" % (len(tiles) + first, fw, fh, OBJ_PAL[g]))
                k += 1
                idx += 1
        tiles += ro.tiles
    assert len(tiles) <= KIT_OBJ_TILE, "the sprites overlap the kit's tiles: raise KIT_OBJ_TILE"
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(names), idx))
    h.append("typedef struct gm_sprite_def { uint16_t tile; uint8_t w, h, pal; } gm_sprite_def;")
    h.append("extern const gm_sprite_def gm_spr[SPR_COUNT];")
    h.append("extern const uint8_t gm_obj_tiles[];\nextern const int gm_obj_tile_count;\nextern const uint16_t gm_obj_pals[48];")
    c.append("const gm_sprite_def gm_spr[SPR_COUNT] = {\n    " + ",\n    ".join(rows) + "};")
    c.append(rsasset.c_bytes("gm_obj_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int gm_obj_tile_count = %d;" % len(tiles))
    c.append(rsasset.c_u16("gm_obj_pals", pals))
    stats.append("OBJ %d" % len(tiles))

    # ---- the asset pack: the music ------------------------------------------------------------------------------------
    music_dir = os.path.join(a.out, "music")
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    pack = [("music/" + os.path.basename(p), p) for p in sorted(glob.glob(os.path.join(music_dir, "*.mod")))]
    entries = []
    for i, (name, path) in enumerate(pack):
        data = open(path, "rb").read()
        c.append(rsasset.c_bytes("pack_%d" % i, data, static=True))
        entries.append('    {"%s", pack_%d, %d}' % (name, i, len(data)))
    c.append("const rs_asset_entry gm_assets[] = {\n" + ",\n".join(entries) + ",\n    {0, 0, 0}};")
    h.append("extern const rs_asset_entry gm_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: tiles %s, %d pack files -> %s" % (", ".join(stats), len(pack), a.out))


if __name__ == "__main__":
    main()
