#!/usr/bin/env python3
"""Leady Squid asset build: sheets and panoramas -> tiles, palettes, maps and
sprites; music -> build/gen/leadysquid/assets.c + assets.h.

    build_assets.py --out build/gen/leadysquid [--art games/leadysquid/art] [--tileset IGNORED]

The BG panoramas (seabed, backdrop) are code-drawn (make_art.py); the
mid-ground is composed from the props sheet (so imported art flows in).
MIT licence, (c) 2026 Pierre-Louis Boyer (8BCraft): games/leadysquid/LICENSE.
"""
import argparse
import colorsys
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)
ROOT = os.path.abspath(os.path.join(GAME, "..", ".."))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "games", "common", "tools"))
import ls_sheets  # noqa: E402
import house_style as hs  # noqa: E402
import rsasset  # noqa: E402
import make_art  # noqa: E402

PAL_SEABED, PAL_THEME0, PAL_MID, PAL_BACK, PAL_LOGO = 1, 2, 6, 7, 5
OBJ_PAL = {"squid": 0, "squid2": 1, "fx": 2, "ui": 3, "squid3": 4, "squid4": 5}
OBJ_CAPS = 6                          # the caps: OBJ 6 + theme parity (draw.c loads the two themes on screen)
# VRAM (absolute tile numbers); each BG layer addresses 1024 tiles from its base
VR_BG1, VR_BG2, VR_BG3, VR_BG4, VR_OBJ = 0, 1024, 1536, 2048, 3072
LOGO_TILE = 320                      # relative to BG1 (font, panel font, 2x-glyph cache, panel frame)


def cname(s):
    return s.upper().replace("-", "_")


def cells8(img, x0, y0, w, h):
    return [rsasset.cell(img, x0 + x * 8, y0 + y * 8, 8, 8) for y in range(h // 8) for x in range(w // 8)]


def frames_of(img, e):
    return [rsasset.cell(img, x, y, w, h) for (x, y, w, h) in ls_sheets.frame_rects(e)]


def canvas_cells(cv):
    """make_art.Canvas -> rsasset cells (8x8, row-major over the whole canvas)."""
    out = []
    for ty in range(cv.h // 8):
        for tx in range(cv.w // 8):
            c = []
            for y in range(8):
                row = []
                for x in range(8):
                    v = cv.p[ty * 8 + y][tx * 8 + x]
                    row.append(None if v is None else rsasset.to555(v))
                c.append(row)
            out.append(c)
    return out


def arr(name, data, fmt="0x%04x", ctype="uint16_t"):
    return "const %s %s[%d] = {%s};" % (ctype, name, len(data), ", ".join(fmt % v for v in data))


def pink_palette(pal555):
    """Player 2: the squid's purples turned pink (hue rotated, other colours kept)."""
    out = []
    for c in pal555:
        r, g, b = [v / 255.0 for v in rsasset.rgb888(c)]
        h, l, s = colorsys.rgb_to_hls(r, g, b)
        if s > 0.25 and 0.70 < h < 0.86:          # the purples
            h = (h + 0.13) % 1.0
            s = min(1.0, s * 1.05)
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        out.append(rsasset.to555((int(r * 255), int(g * 255), int(b * 255))))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--art", default=os.path.join(GAME, "art"))
    ap.add_argument("--tileset", default="", help="ignored (the BG tiles are code-drawn)")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    img = {k: rsasset.load(os.path.join(a.art, v["file"])) for k, v in ls_sheets.SHEETS.items()}
    c, h = ["/* Generated by games/leadysquid/tools/build_assets.py from %s. Do not edit. */" %
            os.path.relpath(a.art, ROOT), '#include "assets.h"\n'], []
    h.append("/* Generated by games/leadysquid/tools/build_assets.py. Do not edit. */")
    h.append("#ifndef LS_ASSETS_H\n#define LS_ASSETS_H\n#include <stdint.h>\n#include \"rs.h\"\n")
    h.append("#define VR_BG1 %d\n#define VR_BG2 %d\n#define VR_BG3 %d\n#define VR_BG4 %d\n#define VR_OBJ %d" %
             (VR_BG1, VR_BG2, VR_BG3, VR_BG4, VR_OBJ))
    h.append("#define PAL_SEABED %d\n#define PAL_THEME0 %d\n#define PAL_MID %d\n#define PAL_BACK %d\n"
             "#define PAL_LOGO %d\n#define LOGO_TILE %d\n#define RAYS_END %d\n" %
             (PAL_SEABED, PAL_THEME0, PAL_MID, PAL_BACK, PAL_LOGO, LOGO_TILE, ls_sheets.RAYS_END))
    stats = []

    # ---- BG2: seabed (512x48) + the obstacle bodies of the four themes ----------------------------
    sea = rsasset.load(os.path.join(a.art, ls_sheets.PANORAMAS["seabed"]["file"]))
    bg2_tiles = [[0] * 64]
    r = rsasset.convert_bg(cells8(sea, 0, 0, 512, 48), 1, pal_base=PAL_SEABED, tile_base=len(bg2_tiles),
                           reserve_blank=False)
    bg2_tiles += r.tiles
    c.append(arr("ls_seabed_map", [m[0] for m in r.metas]))
    c.append(arr("ls_seabed_pal", rsasset.palette16(r.palettes[0])))
    h.append("#define SEABED_W 64\n#define SEABED_H 6")
    h.append("extern const uint16_t ls_seabed_map[SEABED_W * SEABED_H];\nextern const uint16_t ls_seabed_pal[16];")
    theme_pals_bg, theme_pals_obj, body_maps, caps = [], [], [], {}
    for t, th in enumerate(ls_sheets.THEMES):
        body = frames_of(img["obstacles"], ls_sheets.entry(th + "_body"))
        top = frames_of(img["obstacles"], ls_sheets.entry(th + "_cap_top"))
        bot = frames_of(img["obstacles"], ls_sheets.entry(th + "_cap_bottom"))
        allc = rsasset.quantize(body + top + bot, 15)
        body, top, bot = allc[:len(body)], allc[len(body):len(body) + 1], allc[len(body) + 1:]
        cells = []
        for b in body:                              # each 24x16 body -> 6 tiles (3 wide, 2 tall)
            cells += [[row[x * 8:x * 8 + 8] for row in b[y * 8:y * 8 + 8]] for y in range(2) for x in range(3)]
        rb = rsasset.convert_bg(cells, 1, pal_base=PAL_THEME0 + t, tile_base=len(bg2_tiles), reserve_blank=False)
        bg2_tiles += rb.tiles
        body_maps.append([m[0] for m in rb.metas])
        theme_pals_bg.append(rsasset.palette16(rb.palettes[0]))
        caps[th] = (top[0], bot[0])
    h.append("#define BODY_VARIANTS 2\nextern const uint16_t ls_body_map[4][BODY_VARIANTS * 6];")
    h.append("extern const uint16_t ls_theme_bg_pal[4][16];")
    c.append("const uint16_t ls_body_map[4][BODY_VARIANTS * 6] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in m) + "}" for m in body_maps))
    c.append("const uint16_t ls_theme_bg_pal[4][16] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in p) + "}" for p in theme_pals_bg))
    c.append(rsasset.c_bytes("ls_bg2_tiles", rsasset.tiles_bytes(bg2_tiles)))
    c.append("const int ls_bg2_tile_count = %d;" % len(bg2_tiles))
    h.append("extern const uint8_t ls_bg2_tiles[];\nextern const int ls_bg2_tile_count;")
    stats.append("BG2 %d" % len(bg2_tiles))

    # ---- BG3: the mid-ground, composed from the props ---------------------------------------------
    props = make_art.props_from_sheet(img["props"].convert("RGB"))
    mid = make_art.midground(props)
    midcells = canvas_cells(mid)
    if len(set().union(*[rsasset.colors_of(x) for x in midcells])) > 15:
        midcells = rsasset.quantize(midcells, 15)
    r = rsasset.convert_bg(midcells, 1, pal_base=PAL_MID, tile_base=0)
    c.append(rsasset.c_bytes("ls_bg3_tiles", rsasset.tiles_bytes(r.tiles)))
    c.append("const int ls_bg3_tile_count = %d;" % len(r.tiles))
    c.append(arr("ls_mid_map", [m[0] for m in r.metas]))
    c.append(arr("ls_mid_pal", rsasset.palette16(r.palettes[0] if r.palettes else [])))
    h.append("#define MID_W 64\n#define MID_H %d\n#define MID_Y %d" % (mid.h // 8, ls_sheets.PANORAMAS["midground"]["y"]))
    h.append("extern const uint8_t ls_bg3_tiles[];\nextern const int ls_bg3_tile_count;")
    h.append("extern const uint16_t ls_mid_map[MID_W * MID_H];\nextern const uint16_t ls_mid_pal[16];")
    stats.append("BG3 %d" % len(r.tiles))

    # ---- BG4: rays (added) + far reef ---------------------------------------------------------------
    back = rsasset.load(os.path.join(a.art, ls_sheets.PANORAMAS["backdrop"]["file"]))
    r = rsasset.convert_bg(cells8(back, 0, 0, 512, 192), 1, pal_base=PAL_BACK, tile_base=0)
    c.append(rsasset.c_bytes("ls_bg4_tiles", rsasset.tiles_bytes(r.tiles)))
    c.append("const int ls_bg4_tile_count = %d;" % len(r.tiles))
    c.append(arr("ls_back_map", [m[0] for m in r.metas]))
    c.append(arr("ls_back_pal", rsasset.palette16(r.palettes[0])))
    h.append("#define BACK_W 64\n#define BACK_H 24")
    h.append("extern const uint8_t ls_bg4_tiles[];\nextern const int ls_bg4_tile_count;")
    h.append("extern const uint16_t ls_back_map[BACK_W * BACK_H];\nextern const uint16_t ls_back_pal[16];")
    stats.append("BG4 %d" % len(r.tiles))

    # ---- sprites -------------------------------------------------------------------------------------
    groups = [("squid", OBJ_PAL["squid"]), ("fx", OBJ_PAL["fx"]), ("ui", OBJ_PAL["ui"])]
    tiles, rows, names, obj_pals = [], [], [], [0] * 128
    idx = 0
    for g, pal in groups:
        ents = [e for e in ls_sheets.ENTRIES if e.group == g]
        frames = []
        for e in ents:
            frames += frames_of(img[e.sheet], e)
        ro = rsasset.convert_obj(frames)
        p16 = rsasset.palette16(ro.palette)
        obj_pals[pal * 16:pal * 16 + 16] = p16
        if g == "squid":
            obj_pals[16:32] = [0] + pink_palette(p16[1:])
            # players 3 and 4: the house rule (house_style.player_palettes: the purples turned to the two hues
            # farthest from P1's purple and P2's pink)
            sw = hs.player_palettes([rsasset.rgb888(v) for v in p16[1:]], 0.70, 0.86, 0.13)
            for p, key in ((2, "squid3"), (3, "squid4")):
                obj_pals[OBJ_PAL[key] * 16:OBJ_PAL[key] * 16 + 16] = [0] + [rsasset.to555(v) for v in sw[p]]
        k = 0
        for e in ents:
            names.append("SPR_%s = %d" % (cname(e.name), idx))
            for f in range(e.frames):
                first, w, hh = ro.frames[k]
                rows.append("{%d, %d, %d, %d}" % (len(tiles) + first, w, hh, pal))
                k += 1
                idx += 1
        tiles += ro.tiles
    cap_pals = []
    for t, th in enumerate(ls_sheets.THEMES):       # the caps: OBJ palette 6 + theme parity, loaded by draw.c
        ro = rsasset.convert_obj([caps[th][0], caps[th][1]])
        cap_pals.append(rsasset.palette16(ro.palette))
        names.append("SPR_CAP_%s = %d" % (cname(th), idx))
        for first, w, hh in ro.frames:
            rows.append("{%d, %d, %d, %d}" % (len(tiles) + first, w, hh, OBJ_CAPS + t % 2))
            idx += 1
        tiles += ro.tiles
    h.append("enum { %s, SPR_COUNT = %d };" % (", ".join(names), idx))
    h.append("typedef struct ls_sprite_def { uint16_t tile; uint8_t w, h, pal; } ls_sprite_def;")
    h.append("extern const ls_sprite_def ls_spr[SPR_COUNT];")
    h.append("extern const uint8_t ls_obj_tiles[];\nextern const int ls_obj_tile_count;\nextern const uint16_t ls_obj_pals[128];")
    c.append("const ls_sprite_def ls_spr[SPR_COUNT] = {\n    " + ",\n    ".join(rows) + "};")
    c.append(rsasset.c_bytes("ls_obj_tiles", rsasset.tiles_bytes(tiles)))
    c.append("const int ls_obj_tile_count = %d;" % len(tiles))
    c.append(rsasset.c_u16("ls_obj_pals", obj_pals))
    c.append("const uint16_t ls_cap_pals[4][16] = {%s};" % ", ".join(
        "{" + ", ".join("0x%04x" % v for v in p) + "}" for p in cap_pals))
    h.append("extern const uint16_t ls_cap_pals[4][16];\n#define OBJ_CAPS %d" % OBJ_CAPS)
    stats.append("OBJ %d" % len(tiles))

    # ---- title logo (256x64) on BG1 ------------------------------------------------------------------
    limg = rsasset.load(os.path.join(a.art, "title_logo.png"))
    r = rsasset.convert_bg(cells8(limg, 0, 0, 256, 64), 1, pal_base=PAL_LOGO, tile_base=LOGO_TILE)
    c.append(rsasset.c_bytes("ls_logo_tiles", rsasset.tiles_bytes(r.tiles)))
    c.append("const int ls_logo_tile_count = %d;" % len(r.tiles))
    c.append(arr("ls_logo_pal", rsasset.palette16(r.palettes[0])))
    c.append(arr("ls_logo_map", [m[0] for m in r.metas]))
    h.append("#define LOGO_W 32\n#define LOGO_H 8")
    h.append("extern const uint8_t ls_logo_tiles[];\nextern const int ls_logo_tile_count;")
    h.append("extern const uint16_t ls_logo_pal[16];\nextern const uint16_t ls_logo_map[LOGO_W * LOGO_H];")
    stats.append("logo %d" % len(r.tiles))

    # ---- asset pack: music ----------------------------------------------------------------------------
    music_dir = os.path.join(a.out, "music")
    subprocess.check_call([sys.executable, os.path.join(HERE, "make_music.py"), music_dir])
    pack = [("music/" + os.path.basename(p), p) for p in sorted(glob.glob(os.path.join(music_dir, "*.mod")))]
    entries = []
    for i, (name, path) in enumerate(pack):
        data = open(path, "rb").read()
        c.append(rsasset.c_bytes("pack_%d" % i, data, static=True))
        entries.append('    {"%s", pack_%d, %d}' % (name, i, len(data)))
    c.append("const rs_asset_entry ls_assets[] = {\n" + ",\n".join(entries) + ",\n    {0, 0, 0}};")
    h.append("extern const rs_asset_entry ls_assets[];\n#endif")

    open(os.path.join(a.out, "assets.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(a.out, "assets.h"), "w").write("\n".join(h) + "\n")
    print("assets: tiles %s, %d pack files -> %s" % (", ".join(stats), len(pack), a.out))


if __name__ == "__main__":
    main()
